language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER="clang++"

before_script: export CXX="$COMPILER"

script:
  - cd test && cmake . && make
    # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --tool=memcheck --leak-check=full --error-exitcode=1 ./test_all; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./test_all; fi

branches:
  only:
    - master
