language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - valgrind
      env: CXX="g++-4.8"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - valgrind
      env: CXX="clang++-3.5"

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew upgrade --all && brew install cmake; fi

script:
  - cd test && cmake . && make
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --tool=memcheck --leak-check=full -error=exitcode=1 ./test_all; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./test_all; fi

branches:
  only:
    - master
